# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SaveAttributes
                                 A QGIS plugin
 This will save attributes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-03-06
        git sha              : $Format:%H$
        copyright            : (C) 2020 by test
        email                : test@google.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
#from qgis.core import QgsProject 

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .open_reblock_dialog import OpenReblockDialog
import os.path
from qgis.core import QgsProject

import sys 
import qgis_reblock 

class OpenReblock:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SaveAttributes_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Open reblock')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('OpenReblock', message)

    # def select_output_file(self):
    #     filename, _filter = QFileDialog.getSaveFileName(self.dlg, 
    #                         "Select  output file ", "", '*.csv')
    #     self.dlg.lineEdit.setText(filename)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/open_reblock/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Perform reblocking'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Open reblock'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""


        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = OpenReblockDialog()
            #self.dlg.pushButton.clicked.connect(self.self.select_output_file)

        # Populate our combo boxes to choose the input layers
        layers = QgsProject.instance().layerTreeRoot().children()
        layer_names = [layer.name() for layer in layers]
        self.dlg.comboBox_buildings.clear()
        self.dlg.comboBox_buildings.addItems(layer_names)
 
        self.dlg.comboBox_parcels.clear()
        self.dlg.comboBox_parcels.addItems(layer_names)

        self.dlg.comboBox_blocks.clear()
        layer_names_plus_none = ["None"]+layer_names
        layers_plus_none = [None] + layers
        self.dlg.comboBox_blocks.addItems(layer_names_plus_none)

        # Get the output name
        self.dlg.plainTextEdit_outname.clear()

        
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            print("Running open reblock!!")
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            #filename = self.dlg.lineEdit.text()
            #with open(filename, 'w') as output_file:

                # Get the building layer
            building_index = self.dlg.comboBox_buildings.currentIndex()
            building_layer = layers[building_index].layer()

            # And the parcel layer
            parcel_index = self.dlg.comboBox_parcels.currentIndex()
            parcel_layer = layers[parcel_index].layer()

            # And the block (i.e. existing roads) layer
            block_index = self.dlg.comboBox_blocks.currentIndex()
            block_layer = layers_plus_none[block_index]
            if block_layer is not None:
                block_layer = block_layer.layer()

            output_layer_name = self.dlg.plainTextEdit_outname.toPlainText()
            #print(output_layer_name)

            id_col = "block_id"
            qgis_reblock.make_qgis_reblock_layers(building_layer, parcel_layer, block_layer, id_col, output_layer_name)

                # # write header
                # line = ",".join(name for name in fieldnames) + "\n"
                # output_file.write(line)
                # #write feature attributes
                # for f in selectedLayer.getFeatures():
                #   line = ','.join(str(f[name]) for name in fieldnames) + "\n"
                #   output_file.write(line)

layers = QgsProject.instance().layerTreeRoot().children()
layer_names = [layer.name() for layer in layers]
building_layer = layers[2].layer()
parcel_layer = layers[1].layer()
block_layer = None
id_col = 'block_id'
output_layer_name = 'test_out'